### PR TITLE
minor emendations

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by WaitYes** [comment]
Thanks for doing the revisions! I really appreciate it.
The version you've created doesn't run, it brings up an error with from
"class SpaceObject(object)" instead of "class SpaceObject(self)." I'm
guessing this is because you are switching it over to new style classes.
Let me know when it's ready for me to look at! Or if there is anything else
I can do or questions I can answer!
-Jacob

**Comment by jfindlay** [comment]
Yes, that is because I accidentally submitted part of another edit I was working on.  Give me a few more hours and it should be working, hopefully better.

**Comment by WaitYes** [comment]
Awesome! I'm so excited.

**Comment by jfindlay** [comment]
On 10/25/2015 05:30 PM, WaitYes wrote:
> Awesome! I'm so excited.

I could be miscomprehending numpy arithemtic, but shouldn't this line be +=

https://github.com/WaitYes/SpaceshipGame/blob/master/physics_manager.py#L110

You want to add all the forces, not just take the last one calculated,
right?

**Comment by WaitYes** [comment]
Right! That's a good catch.
-Jacob

**Comment by jfindlay** [comment]
Do you know why this code is repeated twice?

https://github.com/WaitYes/SpaceshipGame/blob/master/physics_manager.py#L72-L75

**Comment by jfindlay** [comment]
I think this line should be moved out of the previous for loop:

https://github.com/WaitY
es/SpaceshipGame/blob/master/physics_manager.py#L354

**Pull request merged**
