### PR TITLE
Review

### PR DESCRIPTION
**Pull request by jfindlay**
I am done refactoring the code. I have made numerous changes and probably caused many issues. It is ironic, I know, but I have run out of time for now. You are welcome to merge the changes and work through the likely issues, or imitate the changes on your own.  Since this is your code, either pathway is going to be easier for you than for me.  I am not offloading debugging onto you because I'm lazy or unwilling, but only because I don't have any more time than to hack through the code and rebuild it in the form of something hopefully having more pith, focus, and dynamic stability.

### CODE REVIEW

**Comment by WaitYes** [comment]
Thanks for doing this! I just got the code working, which didn't take too
much doing, and now I'm continuing to review the code in depth to see if I
can understand better the changes you made. I'll let you know when I'm
finished.

I appreciate having an expert help out. Thank you.
-Jacob

**Comment by WaitYes** [comment]
And it does run much faster.

Also, would you mind confirming these emails are getting to you? I still
don't know how the GitHub communication works.

-Jacob

**Comment by jfindlay** [comment]
On 10/27/2015 11:14 AM, WaitYes wrote:
> And it does run much faster.
> 
> Also, would you mind confirming these emails are getting to you? I still
> don't know how the GitHub communication works.

I am glad it is working faster, I didn't think that would be a
consequence.  Also I'm glad it's working at all.  When you comment on a
pull request whether by email or on the site, it is publicly recorded on
the pull request page.


Justin

**Comment by WaitYes** [comment]
Great! Is there a way I can test for certain how fast the program is
running?
-Jacob

**Comment by jfindlay** [comment]
On 10/27/2015 11:26 AM, WaitYes wrote:
> Great! Is there a way I can test for certain how fast the program is
> running?

There are many ways to measure speed.  It depends on what you want to
measure.  There may be an FPS clock as part of you rendering engine to
measure total performance, or you could use timeit (`from timeit import
timeit`) to measure the performance of single program units.  There are
many other great tools available for measuring the performance of python
programs, but I don't remember them right now.  We should meet again
soon to work out such things and strategize the next steps.


Jusitn

**Comment by WaitYes** [comment]
Works for me.
-Jacob

**Comment by WaitYes** [comment]
Where do you live in Salt Lake? I'm trying to make a plan on how, when, and
where to meet. Or we can just Skype.
-Jacob

**Pull request merged**
